### ISSUE TITLE
Not ignoring minimized windows (sometimes)

### ISSUE THREAD

**Issue by zehkira** [zehkira/pytyle1x#1] opened 2021-03-03 12:39 UTC
_Manjaro/XFCE, PyTyle 0.7.9_

When Firefox is minimized, PyTyle treats it as if it wasn't, leaving empty space where it expects the browser to be. As far as I know, this does not happen with any other app.

Need to test with different apps and desktop environments.

**Comment by programical** [comment] 2021-03-03 14:39
Reboot fixed this. Still need to find the cause though.

**Comment by programical** [comment] 2021-03-05 20:12
I still can't consistently reproduce this bug.

**Comment by programical** [comment] 2021-03-20 19:28
I haven't encountered this bug in a while. All attempts to reproduce it failed. Closing for now.

**Comment by programical** [comment] 2021-05-02 13:15
I think I got it. This is caused by Godot.

**Comment by programical** [comment] 2021-05-04 11:05
Today I encountered this issue again despite not using Godot...

**Closed** 2021-08-10 20:58 UTC
Labels: bug, help wanted
